# -*- coding: utf-8 -*-
"""ssc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fM7FQgAG7wWSxd0X3NNr3bNmBYYTU11c
"""

# same
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
!chmod +x Miniconda3-4.5.4-Linux-x86_64.sh
!bash ./Miniconda3-4.5.4-Linux-x86_64.sh -b -f -p /usr/local

!git clone https://github.com/allenai/sequential_sentence_classification.git

# Commented out IPython magic to ensure Python compatibility.
# %cd sequential_sentence_classification/

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# conda create -n allennlp python=3.7
# source activate allennlp
# pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# source activate allennlp
# git config --global url.https://github.com/.insteadOf git://github.com/
# pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# source activate allennlp
# pip install overrides==3.1.0

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# source activate allennlp
# scripts/train.sh tmp_output_dir

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# chmod +x scripts/predict.sh
# source activate allennlp
# sh scripts/predict.sh

